### ISSUE TITLE
Import template

### ISSUE THREAD

**Issue by RichOuellette** [BauhausLuftfahrt/PAXelerate#96]
Attempt import a sample.xmi from template folder. Tries as a project. Tried as a child. Nothing. 
Perhaps .exe still buggy?

**Comment by MicheleMUC** [comment]
**Bug**
Since the release Alpha 0.5 some major modfications to the Ecore meta model structure ocurred. That means, current `*.xmi` templates are not compatible with earlier versions. The project and child import/export function of the Eclipse workbench is currently still defined as _experimental_. Temporary project data is saved in `.cdt`; however, the import does not work so far (#67). Unfourtunately, we won't focus on the enhancement, since these functionalities are provided by the EMF framework.

**Workaround**
Adding or saving a child is the current option to store generated cabins if the Ecore version is equivalent. With the release Alpha-0.6 by the end of this week, the `.xmi` templates will be migrated to the updated Ecore version as well.

**Outlook**
We are currently working on an integrated migration of Ecore meta models (#9) and a futher integration of the EMFstore (#94 and #50) will enable to put them under version control.

The current releases are still pre-releases and can contain bugs. If you face any further difficulties, please attach the log file stored in `workspace/.metadata/` to your bug report. 

Michael
